### PR TITLE
Pin flake8 below 4.0.0

### LINKED ISSUE #18: Flakehell fails with flake8==4.0.0
When installing flakehell in a clean virtualenv it automatically installs the newly released flake8==4.0.0.
But when running flakehell, it fails immediately:

```shell
pip install flakehell flake8==4.0.0
flakehell
```
returns
```text
Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\<user>\<project>\venv\Scripts\flakehell.exe\__main__.py", line 4, in <module>
  File "c:\users\<user>\<project>\venv\lib\site-packages\flakehell\__init__.py", line 5, in <module>
    from ._cli import entrypoint, flake8_entrypoint
  File "c:\users\<user>\<project>\venv\lib\site-packages\flakehell\_cli.py", line 9, in <module>
    from .commands import COMMANDS
  File "c:\users\<user>\<project>\venv\lib\site-packages\flakehell\commands\__init__.py", line 5, in <module>
    from ._baseline import baseline_command
  File "c:\users\<user>\<project>\venv\lib\site-packages\flakehell\commands\_baseline.py", line 6, in <module>
    from .._patched import FlakeHellApplication
  File "c:\users\<user>\<project>\venv\lib\site-packages\flakehell\_patched\__init__.py", line 2, in <module>
    from ._app import FlakeHellApplication
  File "c:\users\<user>\<project>\venv\lib\site-packages\flakehell\_patched\_app.py", line 10, in <module>
    from flake8.options.config import MergedConfigParser, get_local_plugins
ImportError: cannot import name 'MergedConfigParser' from 'flake8.options.config' (c:\users\<user>\<project>\venv\lib\site-packages\flake8\options\config.py)
```

It can be fixed by specifying flake8==3.9.0, but that is not a very satisfying solution.

### LINKED ISSUE #19: Flakehell fails with pre-commit
After flake8 has released version 4.0.0, it is no longer possible to install flakehell as a pre-commit hook. 

An example `.pre-commit-config.yaml`:
```yaml
repos:
  - repo: https://github.com/flakehell/flakehell
    rev: v.0.8.0
    hooks:
      - id: flakehell
 ```
will install flake8==4.0.0 and immediately fail. See #18 .

Specifying a specific version of flake8 does not work. E.g.
```yaml
repos:
  - repo: https://github.com/flakehell/flakehell
    rev: v.0.8.0
    hooks:
      - id: flakehell
        additional_dependencies:
          - flake8==3.9.0
 ```
will fail with exactly the same error. I'm not sure if pre-commit is just ignoring the pinned version, or something else is going on. 

The error has crippled my CI/CD pipelines and the only fix I can think of is to switch back to flake8.

### PR DESCRIPTION
**Pull request by KPLauritzen**
Current version of flakehell does not work with flake8 above 4.0. Pin down flake8 until flakehell has caught up.

Temporarily fixes #18 .
Can fix #19 if a new release is cut.

### CODE REVIEW

**Review by and-semakin — APPROVED** [review]
Thanks!

@sgaynetdinov please consider merging this PR and cutting a new minor release.

**Review by adaamz — APPROVED** [review]

**Comment by mcarans** [comment]
Of interest to those still watching this PR, I have made a [PR](https://github.com/flakehell/flakehell/pull/23) to fix flakehell for flake8 4.0.x. Unfortunately, as with this PR, there is no response. I have raised an [issue](https://github.com/flakehell/flakehell/issues/25) to ask if this project is still being maintained.
